#!/usr/bin/env ruby

# Include required libraries.
require 'optparse'
require 'faraday'
require 'faraday_middleware'
#require 'json'

# Declare variables.
getwowstats_version = '1.0.0'

options = {}

opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage: getwowstats COMMAND [OPTIONS]"
  opt.separator  ""
  opt.separator  "Commands"
  opt.separator  "     char: Name of a valid WoW character."
  opt.separator  ""
  opt.separator  "Options"

  opt.on("-h","--help","help") do
    puts opt_parser
  end
end

opt_parser.parse!

case ARGV[0]
when "char"

  # Declare array.
  character_name = "#{ARGV[2]}"
  locale = "#{ARGV[3]}"
  realm = "#{ARGV[1]}"
 
  # Build URL.
  base_url = 'https://us.api.battle.net/wow'
  url = "#{base_url}/character/#{realm}/#{character_name}?locale=#{locale}&apikey=" + ENV['WOW_API_KEY']

  # Setup HTTPS connection to Blizzard's WoW API.
  conn = Faraday.new(:url => "#{url}") do |faraday|
  faraday.request  :url_encoded             # form-encode POST params
  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
  faraday.response :json, :content_type => /\bjson$/
  
  #  Uncomment below to debug.
  #  faraday.response :logger do | logger |
  #    logger.filter(/(apikey=)(\w+)/,'\1[REMOVED]')
  #  end
  end

  # Make HTTPS GET request against API.
  response = conn.get "#{url}"
  #response.body

  # Save character stats from header response.
  character_stats = response.body 

  # Print out basic character facts.
  puts "Character name: " + character_stats['name']
  puts "Realm: " + character_stats['realm']
  puts "Battlegroup: " + character_stats['battlegroup']
  puts "Class: " + character_stats['class'].to_s
  puts "Race: " + character_stats['race'].to_s
  puts "Gender: " + character_stats['gender'].to_s
  puts "Level: " + character_stats['level'].to_s
  puts "Achievement Points: " + character_stats['achievementPoints'].to_s
  puts "Thumbnail: " + character_stats['thumbnail']
  puts "Calc Class: " + character_stats['calcClass']
  puts "Faction: " + character_stats['faction'].to_s
  puts "Total Honorable Kills: " + character_stats['totalHonorableKills'].to_s

end
